"""DuckDB in-memory rename validation input contracts (phase F6.3).

Structured fixture only — no caller-provided SQL. All executed SQL is
generated by the RIFTLESS service from validated fields.
"""

from __future__ import annotations

import re
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.schemas.changes import NormalizedChange

# ---- Resource limits ---------------------------------------------------------

MAX_COLUMNS = 64
MAX_ROWS = 500
MAX_TOTAL_CELLS = 20_000
MAX_COLUMN_NAME_LENGTH = 128
MAX_VARCHAR_CELL_LENGTH = 4096

_CONTROL_CHAR = re.compile(r"[\x00-\x1f\x7f]")

# Forbidden request-shaped keys that would imply caller SQL / scripts.
_FORBIDDEN_SQL_KEYS = frozenset(
    {
        "sql",
        "setup_sql",
        "migration_sql",
        "assertion_sql",
        "teardown_sql",
        "command",
        "query",
        "script",
    }
)


class DuckDbFixtureColumnType(str, Enum):
    """Allowlisted fixture column types for F6.3.

    Mapped server-side to DuckDB SQL types. Arbitrary DuckDB types are rejected.
    """

    INTEGER = "integer"
    BIGINT = "bigint"
    DOUBLE = "double"
    BOOLEAN = "boolean"
    VARCHAR = "varchar"


# Server-side SQL type mapping (never caller-controlled beyond the enum).
DUCKDB_SQL_TYPE_MAP: dict[DuckDbFixtureColumnType, str] = {
    DuckDbFixtureColumnType.INTEGER: "INTEGER",
    DuckDbFixtureColumnType.BIGINT: "BIGINT",
    DuckDbFixtureColumnType.DOUBLE: "DOUBLE",
    DuckDbFixtureColumnType.BOOLEAN: "BOOLEAN",
    DuckDbFixtureColumnType.VARCHAR: "VARCHAR",
}


def duckdb_sql_type(column_type: DuckDbFixtureColumnType | str) -> str:
    """Map allowlisted fixture type to DuckDB SQL type token."""
    if isinstance(column_type, DuckDbFixtureColumnType):
        key = column_type
    else:
        key = DuckDbFixtureColumnType(column_type)
    return DUCKDB_SQL_TYPE_MAP[key]


class DuckDbFixtureColumn(BaseModel):
    """One column definition in the in-memory fixture table."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=MAX_COLUMN_NAME_LENGTH)
    type: DuckDbFixtureColumnType
    nullable: bool = True

    @field_validator("name")
    @classmethod
    def validate_name(cls, value: str) -> str:
        if value is None or not str(value).strip():
            raise ValueError("column name must not be blank")
        if len(value) > MAX_COLUMN_NAME_LENGTH:
            raise ValueError(
                f"column name must be at most {MAX_COLUMN_NAME_LENGTH} characters"
            )
        if _CONTROL_CHAR.search(value):
            raise ValueError("column name must not contain control characters")
        # Preserve original casing; only reject blank/control.
        return value


class DuckDbFixture(BaseModel):
    """Single-table fixture for DuckDB in-memory rename simulation."""

    model_config = ConfigDict(extra="forbid")

    columns: list[DuckDbFixtureColumn] = Field(min_length=1, max_length=MAX_COLUMNS)
    rows: list[list[Any]] = Field(default_factory=list, max_length=MAX_ROWS)

    @model_validator(mode="after")
    def validate_fixture_shape_and_values(self) -> DuckDbFixture:
        columns = self.columns
        rows = self.rows

        if not columns:
            raise ValueError("fixture must contain at least one column")
        if len(columns) > MAX_COLUMNS:
            raise ValueError(f"fixture must contain at most {MAX_COLUMNS} columns")
        if len(rows) > MAX_ROWS:
            raise ValueError(f"fixture must contain at most {MAX_ROWS} rows")

        # Case-insensitive uniqueness (DuckDB identifier semantic).
        seen: dict[str, str] = {}
        for col in columns:
            key = col.name.casefold()
            if key in seen:
                raise ValueError(
                    f"duplicate column name (case-insensitive): {col.name!r}"
                )
            seen[key] = col.name

        col_count = len(columns)
        cell_count = 0
        for row_index, row in enumerate(rows):
            if not isinstance(row, list):
                raise ValueError(f"row {row_index} must be a list of cell values")
            if len(row) != col_count:
                raise ValueError(
                    f"row {row_index} width {len(row)} does not match column count {col_count}"
                )
            cell_count += len(row)
            if cell_count > MAX_TOTAL_CELLS:
                raise ValueError(
                    f"fixture must contain at most {MAX_TOTAL_CELLS} cells"
                )
            for col_index, (col, value) in enumerate(zip(columns, row, strict=True)):
                _validate_cell(value, col, row_index=row_index, col_index=col_index)

        return self


def _validate_cell(
    value: Any,
    column: DuckDbFixtureColumn,
    *,
    row_index: int,
    col_index: int,
) -> None:
    """Validate a single fixture cell against its column type (no coercion)."""
    loc = f"rows[{row_index}][{col_index}] ({column.name})"
    col_type = column.type
    if isinstance(col_type, DuckDbFixtureColumnType):
        type_value = col_type.value
    else:
        type_value = str(col_type)

    if value is None:
        if not column.nullable:
            raise ValueError(f"{loc}: null is not allowed for non-nullable column")
        return

    if type_value in {"integer", "bigint"}:
        if isinstance(value, bool) or not isinstance(value, int):
            raise ValueError(f"{loc}: expected integer, got {type(value).__name__}")
        return

    if type_value == "double":
        if isinstance(value, bool):
            raise ValueError(f"{loc}: expected number, got bool")
        if not isinstance(value, (int, float)):
            raise ValueError(f"{loc}: expected number, got {type(value).__name__}")
        return

    if type_value == "boolean":
        if not isinstance(value, bool):
            raise ValueError(f"{loc}: expected boolean, got {type(value).__name__}")
        return

    if type_value == "varchar":
        if not isinstance(value, str):
            raise ValueError(f"{loc}: expected string, got {type(value).__name__}")
        if len(value) > MAX_VARCHAR_CELL_LENGTH:
            raise ValueError(
                f"{loc}: varchar value must be at most {MAX_VARCHAR_CELL_LENGTH} characters"
            )
        return

    raise ValueError(f"{loc}: unsupported column type {type_value!r}")


class DuckDbRenameInput(BaseModel):
    """Internal input for the DuckDB in-memory rename validator.

    Rejects arbitrary SQL fields. Uses the existing F5.1 NormalizedChange
    contract for the subject change.
    """

    model_config = ConfigDict(extra="forbid")

    normalized_change: NormalizedChange
    fixture: DuckDbFixture
    required: bool = True

    @model_validator(mode="before")
    @classmethod
    def reject_sql_shaped_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            forbidden = _FORBIDDEN_SQL_KEYS.intersection(data.keys())
            if forbidden:
                raise ValueError(
                    "caller-provided SQL fields are not allowed: "
                    + ", ".join(sorted(forbidden))
                )
        return data

    @model_validator(mode="after")
    def validate_change_type(self) -> DuckDbRenameInput:
        if self.normalized_change.change_type != "rename_column":
            raise ValueError("only rename_column is supported for DuckDB rename checks")
        return self
