"""Server-side DataHub MCP boundary for F8.2.

This package is intentionally not imported by application startup or routes.
"""

from .config import DataHubMCPConfig, load_datahub_mcp_config
from .initialization import DataHubMCPSession, initialize_datahub_mcp
from .tool_discovery import DataHubReadToolCatalog, DataHubReadToolCapability, DataHubReadToolName, discover_datahub_read_tools
from .search_contract import (
    DataHubReadToolDiscoveryBundle,
    DataHubSearchArgumentPlan,
    DataHubSearchContractError,
    DataHubSearchSchemaContract,
    build_datahub_search_argument_plan,
    build_datahub_search_tools_call_request,
    discover_datahub_read_tool_bundle,
    serialize_datahub_search_tools_call_request,
)
from .search_execution import DataHubDatasetSearchRecord, DataHubSearchExecutionError, DataHubSearchExecutionResult, execute_datahub_search
from .asset_resolution import (
    DataHubAssetCandidateResolution,
    DataHubAssetResolutionConfidence,
    DataHubAssetResolutionError,
    DataHubAssetResolutionMethod,
    DataHubAssetResolutionStatus,
    DataHubAssetResolutionSubject,
    RESOLUTION_VERSION,
    build_datahub_asset_resolution_subject,
    build_datahub_asset_search_query,
    build_datahub_resolved_subject_from_resolution,
    resolve_datahub_asset_candidate,
)
from .entity_schema_contract import (
    ENTITY_SCHEMA_BUNDLE_VERSION,
    DataHubEntitySchemaContractError,
    DataHubEntitySchemaContext,
    DataHubEntitySchemaToolDiscoveryBundle,
    DataHubGetEntitiesArgumentPlan,
    DataHubGetEntitiesSchemaContract,
    DataHubListSchemaFieldsArgumentPlan,
    DataHubListSchemaFieldsSchemaContract,
    attest_datahub_get_entities_schema,
    attest_datahub_list_schema_fields_schema,
    bind_datahub_entity_schema_context,
    build_datahub_get_entities_argument_plan,
    build_datahub_get_entities_tools_call_request,
    build_datahub_list_schema_fields_argument_plan,
    build_datahub_list_schema_fields_tools_call_request,
    discover_datahub_entity_schema_tool_bundle,
    serialize_datahub_get_entities_tools_call_request,
    serialize_datahub_list_schema_fields_tools_call_request,
)

__all__ = [
    "DataHubMCPConfig",
    "DataHubMCPSession",
    "initialize_datahub_mcp",
    "load_datahub_mcp_config",
    "DataHubReadToolCatalog",
    "DataHubReadToolCapability",
    "DataHubReadToolName",
    "discover_datahub_read_tools",
    "DataHubReadToolDiscoveryBundle",
    "DataHubSearchArgumentPlan",
    "DataHubSearchContractError",
    "DataHubSearchSchemaContract",
    "build_datahub_search_argument_plan",
    "build_datahub_search_tools_call_request",
    "discover_datahub_read_tool_bundle",
    "serialize_datahub_search_tools_call_request",
    "DataHubDatasetSearchRecord",
    "DataHubSearchExecutionError",
    "DataHubSearchExecutionResult",
    "execute_datahub_search",
    "DataHubAssetCandidateResolution",
    "DataHubAssetResolutionConfidence",
    "DataHubAssetResolutionError",
    "DataHubAssetResolutionMethod",
    "DataHubAssetResolutionStatus",
    "DataHubAssetResolutionSubject",
    "RESOLUTION_VERSION",
    "build_datahub_asset_resolution_subject",
    "build_datahub_asset_search_query",
    "build_datahub_resolved_subject_from_resolution",
    "resolve_datahub_asset_candidate",
    "ENTITY_SCHEMA_BUNDLE_VERSION",
    "DataHubEntitySchemaContractError",
    "DataHubEntitySchemaContext",
    "DataHubEntitySchemaToolDiscoveryBundle",
    "DataHubGetEntitiesArgumentPlan",
    "DataHubGetEntitiesSchemaContract",
    "DataHubListSchemaFieldsArgumentPlan",
    "DataHubListSchemaFieldsSchemaContract",
    "attest_datahub_get_entities_schema",
    "attest_datahub_list_schema_fields_schema",
    "bind_datahub_entity_schema_context",
    "build_datahub_get_entities_argument_plan",
    "build_datahub_get_entities_tools_call_request",
    "build_datahub_list_schema_fields_argument_plan",
    "build_datahub_list_schema_fields_tools_call_request",
    "discover_datahub_entity_schema_tool_bundle",
    "serialize_datahub_get_entities_tools_call_request",
    "serialize_datahub_list_schema_fields_tools_call_request",
]
